### ISSUE TITLE
Sync Project Flow with our Services structure

### ISSUE THREAD

**Issue by marcoow** [mainmatter/playbook#41]
The project flow we're currently describing is in sync with our service structure in terms of content but not necessarily in terms of structure. We'll want to make sure that the main phases in the flow are

* Product Strategy
* Product Design
* Product Development

### TODO

- [x] rename _"Discovery"_ to _"Product Strategy"_
- [x] rename _"Conception"_ to _"Product Design"_
- [x] rename "Execution" to "Product Development"
- [x] rename "Full Service" project flow to "Digital Products"
