### ISSUE TITLE
Update Consulting Project Procedure to be in line with new services

### ISSUE THREAD

**Issue by marcoow** [mainmatter/playbook#57]
We are no longer splitting the consulting services into team augmentation and full project delivery but into team augmentation and training/tutoring. We need to update the consulting project procedure to reflect that.

### TODO

- [x] remove "Project Delivery"
- [x] add "Training and Tutoring" instead; this is basically just one paragraph explaining the various things we can do (often based on the findings in the review)
- [x] update "Product Team Introduction" to reflect when doing tutoring/training we do not actually merge with the client's team necessarily
